trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "DockerBuildandPush"
    displayName: "Docker Build and Push"
    jobs:
      - job: "Install"
        displayName: "Docker Build job"
        pool:
          vmImage: "ubuntu-16.04"
        steps:
          - task: Bash@3
            displayName: Get-Date-forTag
            inputs:
              script: |
                curdate=echo $(Date:yyyyMMdd)
                echo "##vso[task.setvariable variable=tagdate;]$curdate"

          - task: Docker@2
            displayName: "Docker Login"
            name: dockerlogin
            inputs:
              containerRegistry: "sc-docker"
              command: login
          - task: Docker@2
            displayName: "Docker Build Task"
            name: dockertask
            inputs:
              containerRegistry: "sc-docker"
              repository: kgopi1/cicd-demo
              container: kgopi1/cicd-demo
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: $(tagdate)
