# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  name: dockerlogin
  displayName: Docker Login
  inputs:
    containerRegistry: 'sc-docker'
    command: login
    
  
- task: Docker@2
  displayName: 'Docker build'
  inputs:
    containerRegistry: 'sc-docker'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: kgopi1/cicd-demo

- task: Docker@2
  displayName: 'Docker push'
  inputs:
    containerRegistry: 'sc-docker'
    command: 'push'
    Dockerfile: '**/Dockerfile'
    tags: kgopi1/cicd-demo

